a = 16;
b = 7;
ans1 = a+b;
print("Addition of",a,"and",b,"is->",ans1);
ans2 = a-b;
print("Subtracion of",a,"and",b,"is->",ans2);
ans3 = a*b;
print("Multiplication of",a,"and",b,"is->",ans3);
ans4 = a/b;
print("Division of",a,"and",b,"is->",ans4);
ans5 = a**b;
print("Exponential of",a,"and",b,"is->",ans5);
ans6 = a//b;
print("Floor Division of",a,"and",b,"is->",ans6);
ans7 = a%b;
print("Modulus of",a,"and",b,"is->",ans7);